# Site settings
title: Josh's website
email: jbayy334@gmail.com
description: I am a student at UAlbany
url: jbay334.github.io
github_username: jbay334

# Build settings
markdown: kramdown
permalink: pretty
